apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBSqDJ6PL1ogufHvuAkTpsMW2moNj25NfY873sxHV3asUGGhh9yI8jg1umjwNMGuENq0vAB2fnDZ1qHWkteCz5HLavF5htYKI80KTfV+JsbfwpvRQImNxS2NhmgVJKmHUJBsXxDGW+XWSZOkQKm/Z8CwWtvgXBasGwKu8+RCTZI+kTsVbj3qW/s42aIPqVH1XubQuQp8OYN5CBUzbmJmfkfYlqk6XOiTlFLVEAxpouZgndCwGQTCnkrMDQY2D6OaBL1Xiyrn5Kk6hupUfCPSl+4dECTS36EYWll5JslHDVX6jrmY1IMDPg/SANrTv05ue0MOFZF9wFHOobsNPAwTHtpmY/7sboI0lpzljkDWrUr1Pz5C6XqhGdb7t3Ec+II/wea9FamN1W9XcB/hdv6cFgBWQp01F/vjgHHvmGbM+lDfOKGdLSqCbCVsG3rxvW9EV807y1i9sKEuwqCk9vSM+vM3ONQpAc5A8xxoriq4dgqq/c7uiZoXMt2r5E1qXTHZvq5Wj0h9jyTdixblUFJkIcYUPv+MQlakyQNuy7NApvNy4Ivsr3A+eEqx5Cb9FDwxaIIszRcX1qcOIUqJJwvnTH8opy1TbiBodaOjkP2S61sKhq5BTkLQmdxgGVo6IpuO8b41rho6lz8tel6A7wFvDki5jOd8Df0+qU7T6nx0y4a7BVjeVUxeT5o6VuTIqlxBYT8w+benwDmEoQPGvrLxUaHOojitI9OkoZh3Cz/Mhov8cZ82cYxfIYHunjc4mF5oqFfjiZNhPBjU++xQtCbzns4U7Utrl2BQh2LbmqdtgHyPkumrdRVcVI3OGUQao4Zswp3j/e45s5JbIQAW0ZACKaLg5dd6ZC8SgVUi/yK5itI7dCWxEeWaSZFi3nKA25nub2c9WgaAcxgpulAQa0=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

